title: joelcponte
description: > # this means to ignore newlines until "baseurl:"
  This blog is about topics related to the data science universe. More specifically: machine learning, data visualization, statistics, python, R and so on.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Joel Ponte # add your name
author-img: joel-ponte.jpg # add your photo
about-author: #I write about data science. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: joelcponte # add your Github handle
social-linkedin: joelcponte # add your Linkedin handle
social-email: joelcponte@gmail.com # add your Email address

# Disqus
discus-identifier: machine-learning # add your discus identifier

# Tracker
analytics: "UA-116902624-1" # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
